DWTCMS.Web/Areas/admin/Controllers/CmsPageController.cs
using DWTCMS.Core.Infrastructure;
using DWTCMS.Data.Model;
using DWTCMS.Service.Config;
using DWTCMS.Web.Areas.admin.ViewModel;
using DWTCMS.Web.Areas.admin.ViewModel.Admin.CmsPage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DWTCMS.Web.Areas.admin.Controllers
{
    [LoginControl]
    public class CmsPageController : Controller
    {
        private readonly ICmsPageRepository _cmsPageRepository;
        public CmsPageController(ICmsPageRepository cmsPageRepository)
        {
            _cmsPageRepository = cmsPageRepository;
        }
        public ActionResult Index()
        {
            var model = _cmsPageRepository.GetAll().ToList();

            var viewModel = new List<CmsPageList>();
            if (model.Any())
            {
                foreach (var item in model)
                {
                    var vm = new CmsPageList
                    {
                        Id = item.ID,
                        PageValue = item.PageValue.ToString()
                    };
                    viewModel.Add(vm);
                }
            }
            return View(viewModel);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData[AppCons.TempDataError] = "İçerik sayfası bulunamadı";
                return RedirectToAction("Index");
            }
            var cmsPage = _cmsPageRepository.GetById(id.Value);
            if (cmsPage==null)
            {
                TempData[AppCons.TempDataError] = "İçerik sayfası bulunamadı";
                return RedirectToAction("Index");
            }
            var uModel = new CmsPageEdit
            {
                PageDescription = cmsPage.PageDescription,
                PageShortDescription = cmsPage.PageShortDescription,
                PageValue = (int)cmsPage.PageValue
            };
            return View(uModel);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(CmsPageEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            CmsPage uModel = new CmsPage()
            {
                PageDescription = model.PageDescription,
                PageShortDescription = model.PageShortDescription,
                ID = model.ID,
                PageValue = (PageValue)model.PageValue
            };
            try
            {
                _cmsPageRepository.Update(uModel);
                _cmsPageRepository.Save();


                TempData[AppCons.TempDataSuccess] = "İçerik sayfası başarıyla düzenlendi";
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
    }
}

DWTCMS.Web/Areas/admin/Views/CmsPage/Edit.cshtml
@model DWTCMS.Web.Areas.admin.ViewModel.Admin.CmsPage.CmsPageEdit

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-green-sharp bold">İçrerik Sayfası Güncelle</span>
                </div>
                <div class="actions">
                    <input type="submit" value="Güncelle" class="btn green" />
                    <a href="@Url.Action("Index","CmsPage")" class="btn red">
                        İptal
                    </a>
                </div>
            </div>
            <div class="tabbable-line">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab_1_1" data-toggle="tab"> Türkçe </a>
                    </li>
                    <li>
                        <a href="#tab_1_2" data-toggle="tab"> İngilizce </a>
                    </li>
                    <li>
                        <a href="#tab_1_3" data-toggle="tab"> Rusça </a>
                    </li>
                    <li>
                        <a href="#tab_1_4" data-toggle="tab"> Arapça </a>
                    </li>
                </ul>
                <div class="tab-content">
                    @Html.HiddenFor(model => model.PageValue)
                    <div class="tab-pane fade active in" id="tab_1_1">
                        <div class="form-group">
                            @Html.LabelFor(model => model.PageShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PageShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PageShortDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PageDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PageDescription, new { htmlAttributes = new { @class = "ckeditor" } })
                                @Html.ValidationMessageFor(model => model.PageDescription, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab_1_2">

                    </div>
                    <div class="tab-pane fade" id="tab_1_3">

                    </div>
                    <div class="tab-pane fade" id="tab_1_4">

                    </div>
                </div>
            </div>
        </div>
    </div>
}

DWTCMS.Web/Areas/admin/Views/CmsPage/Index.cshtml
@model IEnumerable<DWTCMS.Web.Areas.admin.ViewModel.Admin.CmsPage.CmsPageList>

@{
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-layers"></i>
                        <span class="caption-subject bold uppercase">İÇERİK SAYFALARI</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="myTable">
                    <thead>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.PageValue)
                            </th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PageValue)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit","CmsPage", new { id = item.Id })" class="btn btn-sm green">
                                        <i class="fa fa-pencil"></i>
                                        Düzenle
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>