DWTCMS.Web/Areas/admin/Controllers/SlideController.cs
using DWTCMS.Core.Infrastructure;
using DWTCMS.Data.Model;
using DWTCMS.Service.Config;
using DWTCMS.Web.Areas.admin.ViewModel;
using DWTCMS.Web.Areas.admin.ViewModel.Admin.Slide;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DWTCMS.Web.Areas.admin.Controllers
{
    [LoginControl]
    public class SlideController : Controller
    {
        private readonly ISlideRepository _slideRepository;

        public SlideController(ISlideRepository slideRepository)
        {
            _slideRepository = slideRepository;
        }
        public ActionResult Index()
        {
            var model = _slideRepository.GetAll().ToList().Select(x => new { x.ID, x.Order, x.Title, x.IsOpen, x.Path }).OrderBy(y => y.Order);

            var viewModel = new List<SlideList>();

            if (model.Any())
            {
                foreach (var p in model)
                {
                    var vm = new SlideList
                    {
                        ID = p.ID,
                        DisplayOrder = p.Order,
                        Path = p.Path,
                        Published = p.IsOpen,
                        Title = p.Title
                    };
                    viewModel.Add(vm);
                }
            }
            return View(viewModel);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SlideCreateOrEdit model, HttpPostedFileBase slideImage)
        {
            string guid = Guid.NewGuid().ToString();

            if (slideImage != null && slideImage.ContentLength > 0)
            {
                slideImage.SaveAs(Path.Combine(Server.MapPath("~/Areas/admin/Content/img/slide/"), guid + slideImage.FileName));
            }
            var cModel = new Slide
            {
                Title = model.Title,
                Path = model.Path = guid + slideImage.FileName,
                Order = model.Order,
                IsOpen = model.IsOpen
            };
            try
            {
                _slideRepository.Insert(cModel);
                _slideRepository.Save();
                TempData[AppCons.TempDataSuccess] = "Slayt başarıyla eklendi";
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var slide = _slideRepository.GetById(id.Value);
            if (slide == null)
            {
                return HttpNotFound();
            }
            SlideCreateOrEdit uModel = new SlideCreateOrEdit()
            {
                ID = slide.ID,
                Title = slide.Title,
                IsOpen = slide.IsOpen,
                Order = slide.Order,
                Path=slide.Path
            };
            return View(uModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SlideCreateOrEdit slide, HttpPostedFileBase slideImage)
        {
            var realSlide = _slideRepository.GetById(slide.ID);
            string guid=string.Empty;
            if (slideImage == null || slideImage.ContentLength <= 0)
            {
                slide.Path = realSlide.Path;
                if (!ModelState.IsValid)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                System.IO.File.Delete(Server.MapPath("~/Areas/admin/Content/img/slide/" + realSlide.Path));
                guid = Guid.NewGuid().ToString();
                slide.Path = guid + slideImage.FileName;
                slideImage.SaveAs(Path.Combine(Server.MapPath("~/Areas/admin/Content/img/slide/"), guid + slideImage.FileName));
            }
            Slide uModel = new Slide()
            {
                ID=slide.ID,
                Title=slide.Title,
                Order=slide.Order,
                Path=slide.Path,
                IsOpen=slide.IsOpen
            };
            try
            {
                _slideRepository.Update(uModel);
                _slideRepository.Save();
                TempData[AppCons.TempDataSuccess] = "Slayt başarıyla düzenlendi";
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            try
            {
                System.IO.File.Delete(Server.MapPath("~/Areas/admin/Content/img/slide/" + _slideRepository.GetById(id.Value).Path));
                _slideRepository.Delete(id.Value);
                _slideRepository.Save();
                TempData[AppCons.TempDataSuccess] = "Slayt başarıyla silindi";
            }
            catch (Exception)
            {
                throw;
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult GetImg(int Id)
        {
            var model = _slideRepository.GetById(Id);
            return Json(model.Path, JsonRequestBehavior.AllowGet);
        }
    }
}

DWTCMS.Web/Areas/admin/Views/Slide/Create.cshtml
@model DWTCMS.Web.Areas.admin.ViewModel.Admin.Slide.SlideCreateOrEdit
@using (Html.BeginForm("Create", "Slide", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-green-sharp bold">Yeni Slayt</span>
                </div>
                <div class="actions">
                    <input type="submit" value="Kaydet" class="btn green" />
                    <a href="@Url.Action("Index","Slide")" class="btn red">
                        İptal
                    </a>
                </div>
            </div>
            <div class="tabbable-line">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab_1_1" data-toggle="tab"> Türkçe </a>
                    </li>
                    <li>
                        <a href="#tab_1_2" data-toggle="tab"> İngilizce </a>
                    </li>
                    <li>
                        <a href="#tab_1_3" data-toggle="tab"> Rusça </a>
                    </li>
                    <li>
                        <a href="#tab_1_4" data-toggle="tab"> Arapça </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade active in" id="tab_1_1">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsOpen, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="icheck-list">
                                    <input type="checkbox" name="IsOpen" value="true" class="icheck" checked />
                                    @Html.ValidationMessageFor(model => model.IsOpen, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                        <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=Resim+Yok" alt="">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                    <div>
                                        <span class="btn red btn-outline btn-file">
                                            <span class="fileinput-new"> Resim Seç </span>
                                            <span class="fileinput-exists"> Değiştir </span>
                                            <input type="file" name="slideImage" accept="image/*">
                                        </span>
                                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Sil </a>
                                    </div>
                                </div>
                                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane fade" id="tab_1_2">

                    </div>
                    <div class="tab-pane fade" id="tab_1_3">

                    </div>
                    <div class="tab-pane fade" id="tab_1_4">

                    </div>
                </div>
            </div>
        </div>
    </div>
}

DWTCMS.Web/Areas/admin/Views/Slide/Edit.cshtml
@model DWTCMS.Web.Areas.admin.ViewModel.Admin.Slide.SlideCreateOrEdit
@using (Html.BeginForm("Edit", "Slide", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-green-sharp bold">Slayt Düzenle</span>
                </div>
                <div class="actions">
                    <input type="submit" value="Güncelle" class="btn green" />
                    <a href="@Url.Action("Index","Slide")" class="btn red">
                        İptal
                    </a>
                </div>
            </div>
            <div class="tabbable-line">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab_1_1" data-toggle="tab"> Türkçe </a>
                    </li>
                    <li>
                        <a href="#tab_1_2" data-toggle="tab"> İngilizce </a>
                    </li>
                    <li>
                        <a href="#tab_1_3" data-toggle="tab"> Rusça </a>
                    </li>
                    <li>
                        <a href="#tab_1_4" data-toggle="tab"> Arapça </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade active in" id="tab_1_1">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsOpen, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="icheck-list">
                                    @if (Model.IsOpen)
                                    {
                                        <input type="checkbox" name="IsOpen" value="true" class="icheck" checked />
                                    }
                                    else
                                    {
                                        <input type="checkbox" name="IsOpen" value="true" class="icheck" />
                                    }
                                    @Html.ValidationMessageFor(model => model.IsOpen, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                        <img src="~/Areas/admin/content/img/slide/@Url.Content(Model.Path)" alt="">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                    <div>
                                        <span class="btn red btn-outline btn-file">
                                            <span class="fileinput-new"> Resim Seç </span>
                                            <span class="fileinput-exists"> Değiştir </span>
                                            <input type="file" name="slideImage" accept="image/*">
                                        </span>
                                        <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> Sil </a>
                                    </div>
                                </div>
                                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class="tab-pane fade" id="tab_1_2">

                    </div>
                    <div class="tab-pane fade" id="tab_1_3">

                    </div>
                    <div class="tab-pane fade" id="tab_1_4">

                    </div>
                </div>
            </div>
        </div>
    </div>
}


<script src="~/Content/scripts/jquery.validate.min.js"></script>

DWTCMS.Web/Areas/admin/Views/Slide/Index.cshtml
@model IEnumerable<DWTCMS.Web.Areas.admin.ViewModel.Admin.Slide.SlideList>
@{
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Delete", "Slide", FormMethod.Post, new { @id = "deleteForm" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="id" id="id" value="" />
}
<div class="row">
    <div class="col-md-12">
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-docs"></i>
                    <span class="caption-subject bold uppercase">SLAYTLAR</span>
                </div>
                <div class="actions">
                    <a href="@Url.Action("Create","Slide")" class="btn green">
                        <i class="fa fa-plus"></i>
                        Yeni Kayıt
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table" id="myTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Path)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DisplayOrder)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Published)
                            </th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <span><i class="fa fa-image hoverImgSlide" data-id="@item.ID"><img class="hidden" src="" /></i></span>
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Published)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit","Slide", new { id = item.ID })" class="btn btn-sm green">
                                        <i class="fa fa-pencil"></i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-sm green sweet-4" data-title="@item.Title" data-id="@item.ID">
                                        <i class="fa fa-trash-o"></i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>